name: News Bot Runner

on:
  schedule:
    # Runs every 60 minutes. 
    # NOTE: GitHub Actions cron is not perfectly precise, it might be slightly delayed.
    - cron: '0 * * * *' 
  workflow_dispatch: # Allows you to manually click "Run" for testing

permissions:
  contents: write # IMPORTANT: Allows the bot to save the history file back to the repo

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install tweepy feedparser

      - name: Run Bot Script
        env:
          # These pull the keys you saved in GitHub Secrets
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: python bot.py

      - name: Commit and Push History
        # This step saves the updated posted_ids.txt back to your repo
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add posted_ids.txt
          # Only commit if the file actually changed (i.e., we posted something new)
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update post history" && git push)
